use serde::{Deserialize, Serialize};

use crate::sage_compat::SageEdition;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoiceSchema {
    pub table_piece: String,
    pub table_ligne: String,
    pub table_article: String,
    pub table_tiers: String,
    pub table_roletiers: String,
    pub table_journal: String,

    pub col_piece_oid: String,
    pub col_piece_numero: String,
    pub col_piece_date: String,
    pub col_piece_reference: String,
    pub col_piece_tiers: String,
    pub col_piece_nature: String,
    pub col_piece_statut: String,
    pub col_piece_total_ht: String,
    pub col_piece_total_ttc: String,
    pub col_piece_devise: String,

    pub col_ligne_piece: String,
    pub col_ligne_article: String,
    pub col_ligne_libelle: String,
    pub col_ligne_qte: String,
    pub col_ligne_pu_ht: String,
    pub col_ligne_taux_tva: String,
    pub col_ligne_montant_ht: String,
    pub col_ligne_montant_ttc: String,
    pub col_ligne_remise: String,
    pub col_ligne_ordre: String,

    pub col_article_code: String,
    pub col_article_libelle: String,
    pub col_article_pu: String,
    pub col_article_tva: String,
    pub col_article_ref: String,
}

impl InvoiceSchema {
    pub fn for_edition(edition: &SageEdition) -> InvoiceSchema {
        match edition {
            SageEdition::Sage1000 => InvoiceSchema {
                table_piece: "TPIECE".into(),
                table_ligne: "TLIGNEPI\u{00C8}CE".into(),
                table_article: "TARTICLE".into(),
                table_tiers: "TTIERS".into(),
                table_roletiers: "TROLETIERS".into(),
                table_journal: "TJOURNAL".into(),
                col_piece_oid: "oid".into(),
                col_piece_numero: "numero".into(),
                col_piece_date: "pDate".into(),
                col_piece_reference: "reference".into(),
                col_piece_tiers: "oidTiers".into(),
                col_piece_nature: "NaturePiece".into(),
                col_piece_statut: "statut".into(),
                col_piece_total_ht: "totalHT".into(),
                col_piece_total_ttc: "totalTTC".into(),
                col_piece_devise: "oiddevise".into(),
                col_ligne_piece: "oidpiece".into(),
                col_ligne_article: "oidarticle".into(),
                col_ligne_libelle: "libelle".into(),
                col_ligne_qte: "quantite".into(),
                col_ligne_pu_ht: "prixUnitaireHT".into(),
                col_ligne_taux_tva: "tauxTVA".into(),
                col_ligne_montant_ht: "montantHT".into(),
                col_ligne_montant_ttc: "montantTTC".into(),
                col_ligne_remise: "remise".into(),
                col_ligne_ordre: "ordre".into(),
                col_article_code: "code".into(),
                col_article_libelle: "Caption".into(),
                col_article_pu: "prixVente".into(),
                col_article_tva: "tauxTVA".into(),
                col_article_ref: "reference".into(),
            },
            SageEdition::Sage100 => InvoiceSchema {
                table_piece: "F_PIECE".into(),
                table_ligne: "F_PIECEL".into(),
                table_article: "F_ARTICLE".into(),
                table_tiers: "F_TIERS".into(),
                table_roletiers: String::new(),
                table_journal: "F_JOURNAL".into(),
                col_piece_oid: "EC_No".into(),
                col_piece_numero: "EC_Piece".into(),
                col_piece_date: "EC_Date".into(),
                col_piece_reference: "EC_RefPiece".into(),
                col_piece_tiers: "CT_Num".into(),
                col_piece_nature: "EC_Type".into(),
                col_piece_statut: "statut".into(),
                col_piece_total_ht: "totalHT".into(),
                col_piece_total_ttc: "totalTTC".into(),
                col_piece_devise: "EC_Devise".into(),
                col_ligne_piece: "EC_No".into(),
                col_ligne_article: "AR_Ref".into(),
                col_ligne_libelle: "DL_Design".into(),
                col_ligne_qte: "DL_Qte".into(),
                col_ligne_pu_ht: "DL_PrixUnitaire".into(),
                col_ligne_taux_tva: "DL_Taxe1".into(),
                col_ligne_montant_ht: "DL_MontantHT".into(),
                col_ligne_montant_ttc: "DL_MontantTTC".into(),
                col_ligne_remise: "DL_Remise01".into(),
                col_ligne_ordre: "DL_No".into(),
                col_article_code: "AR_Ref".into(),
                col_article_libelle: "AR_Design".into(),
                col_article_pu: "AR_PrixVen".into(),
                col_article_tva: "AR_TauxTva".into(),
                col_article_ref: "AR_Ref".into(),
            },
            _ => InvoiceSchema {
                table_piece: String::new(),
                table_ligne: String::new(),
                table_article: String::new(),
                table_tiers: String::new(),
                table_roletiers: String::new(),
                table_journal: String::new(),
                col_piece_oid: String::new(),
                col_piece_numero: String::new(),
                col_piece_date: String::new(),
                col_piece_reference: String::new(),
                col_piece_tiers: String::new(),
                col_piece_nature: String::new(),
                col_piece_statut: String::new(),
                col_piece_total_ht: String::new(),
                col_piece_total_ttc: String::new(),
                col_piece_devise: String::new(),
                col_ligne_piece: String::new(),
                col_ligne_article: String::new(),
                col_ligne_libelle: String::new(),
                col_ligne_qte: String::new(),
                col_ligne_pu_ht: String::new(),
                col_ligne_taux_tva: String::new(),
                col_ligne_montant_ht: String::new(),
                col_ligne_montant_ttc: String::new(),
                col_ligne_remise: String::new(),
                col_ligne_ordre: String::new(),
                col_article_code: String::new(),
                col_article_libelle: String::new(),
                col_article_pu: String::new(),
                col_article_tva: String::new(),
                col_article_ref: String::new(),
            },
        }
    }

    pub fn is_supported(&self) -> bool {
        !self.table_piece.is_empty() && !self.table_ligne.is_empty()
    }
}
